/**
 * Home-screen suggestion chip — the four cards above the composer on `/`.
 * Generated by the meta-agent from the connected DB's knowledge pack and
 * cached in `home_suggestions` keyed by fingerprint.
 */
export type ChipIcon = "chart" | "database" | "file" | "users" | "trending" | "clock";

export interface Suggestion {
  icon: ChipIcon;
  label: string;
  prompt: string;
}

export const CHIP_ICONS: ChipIcon[] = [
  "chart",
  "database",
  "file",
  "users",
  "trending",
  "clock",
];

/**
 * Last-resort chips when the agent hasn't filled in the DB yet. Deliberately
 * vague — they shouldn't lock the model into any one schema.
 */
export const FALLBACK_SUGGESTIONS: Suggestion[] = [
  {
    icon: "database",
    label: "Map the data",
    prompt: "What tables exist in this database, and which are the central ones?",
  },
  {
    icon: "chart",
    label: "Recent activity",
    prompt: "What's been happening in the data over the last 30 days?",
  },
  {
    icon: "trending",
    label: "Top items",
    prompt: "Show me the top 10 records by the most meaningful metric you can find.",
  },
  {
    icon: "file",
    label: "Inspect a record",
    prompt: "Pick a recent record from a meaningful table and walk me through its details.",
  },
];
